services:
    gabriel.medals.admin.controller:
        class: gabriel\medals\controller\admin_controller
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    gabriel.medals.listener:
        class: gabriel\medals\event\listener
        arguments:
            - '@template'
            - '@dbal.conn'
            - '@config'
            - '%core.root_path%'
        tags:
            - { name: event.listener }